# Generated by Django 4.2.4 on 2023-09-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='summary',
        ),
        migrations.AddField(
            model_name='articol',
            name='summary',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
