# Generated by Django 4.2.5 on 2023-09-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0003_alter_articol_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articol',
            name='contents',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
