# Generated by Django 4.2.4 on 2023-09-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0002_remove_item_summary_articol_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articol',
            name='slug',
            field=models.SlugField(max_length=10),
        ),
    ]
