# Generated by Django 4.2.6 on 2023-10-20 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 8, 40, 6, 242158, tzinfo=datetime.timezone.utc)),
        ),
    ]
