# Generated by Django 4.2.6 on 2023-10-24 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_article_created_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog_picture',
            field=models.ImageField(blank=True, default='./media/images/none_picture', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 9, 56, 43, 824226, tzinfo=datetime.timezone.utc)),
        ),
    ]
